// Previously auto-generated by Lovable. Replaced with native Supabase OAuth
// so the app works on any host (Vercel, Render, etc.) without Lovable cloud.

import { supabase } from "../supabase/client";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

type OAuthProvider = "google" | "apple" | "microsoft";

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: OAuthProvider, opts?: SignInOptions) => {
      const redirectTo =
        opts?.redirect_uri ?? `${window.location.origin}/auth/callback`;

      const { data, error } = await supabase.auth.signInWithOAuth({
        provider,
        options: {
          redirectTo,
          queryParams: opts?.extraParams,
        },
      });

      if (error) {
        return { error, redirected: false };
      }

      // Supabase redirects the browser automatically when a URL is returned.
      // Return redirected: true so callers know not to navigate programmatically.
      if (data?.url) {
        window.location.href = data.url;
        return { redirected: true, error: null };
      }

      return { redirected: false, error: null };
    },
  },
};
